import React,{useState,useEffect} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [data, setData] = useState([]);
  useEffect(() => {
    let requestOptions = {
      method: 'GET',
      redirect: 'follow'
    };
    fetch( "/drivers", requestOptions)
      .then(response =>response.json())
      .then(restule => {
        // console.log(restule.data);
        setData(restule.data);
      })
      .catch(error => console.log('error',error))

  },[]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          F1 2021 車手名單
        </p>

        <div className={styles.grid}>
          {
            data.map((da, idx) => {
              return (
                <a href={`/dirver/${da.no}`} className={styles.card} key={idx}>
                  <h2>{da.name} &rarr;</h2>
                  <p>{da.team} / {da.no}</p>
                </a>
              )
            })
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        </a>
      </footer>
    </div>
  )
}
